name: SGSI_Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Load Configuration
        uses: falti/dotenv-action@v3.0.0
        id: config
        with:
          path: config.env

      - name: Check Configuration
        run: |
          function required () { if ! [[ "$1" ]]; then echo "$2 variable can't be null." && exit 1; fi }
          required "${{ steps.config.outputs.ROM_URL }}" "ROM_URL"
          required "${{ steps.config.outputs.BUILD_TYPE }}" "BUILD_TYPE"
          required "${{ steps.config.outputs.OS_TYPE }}" "OS_TYPE"
          required "${{ steps.config.outputs.ZIP_NAME }}" "ZIP_NAME"
          required "${{ steps.config.outputs.VERSION }}" "VERSION"
          required "${{ steps.config.outputs.REPACK_NAME }}" "REPACK_NAME"

      - name: Cleanup workspace
        run: |
          df -h
          echo "跳过危险的系统清理操作"

      - name: Initializing Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y git wget zip unzip curl axel

      - name: Cloning SGSI source code
        run: |
          git clone --recurse-submodules https://github.com/xiaoxindada/SGSI-build-tool.git -b 12 $GITHUB_WORKSPACE/SGSI-build-tool

      - name: Setup sGSI tools requirements
        run: |
          sudo sed -i 's/USE_MIRROR_FOR_PIP=true/USE_MIRROR_FOR_PIP=false/' $GITHUB_WORKSPACE/SGSI-build-tool/setup.sh
          sudo bash $GITHUB_WORKSPACE/SGSI-build-tool/setup.sh
          java -version

      - name: Build SGSI
        run: |
          cd $GITHUB_WORKSPACE/SGSI-build-tool
          sudo bash ./url2SGSI.sh "${{ steps.config.outputs.ROM_URL }}" "${{ steps.config.outputs.OS_TYPE }}" "${{ steps.config.outputs.BUILD_TYPE }}"

      - name: Repack Output File
        run: |
          cd $GITHUB_WORKSPACE/SGSI-build-tool
          mkdir -p upload
          
          # 使用zip分卷功能
          zip -s 1024m "upload/${{ steps.config.outputs.REPACK_NAME }}.zip" SGSI/*
          
          ls -lh upload/

      - name: Upload SGSI to GH-Release
        uses: ncipollo/release-action@v1.8.6
        with:
          artifacts: ${{ github.workspace }}/SGSI-build-tool/upload/*
          name: "${{ steps.config.outputs.OS_TYPE }}${{ steps.config.outputs.BUILD_TYPE }}-Android${{ steps.config.outputs.VERSION }}-unpack"
          tag: "${{ steps.config.outputs.OS_TYPE }}${{ steps.config.outputs.BUILD_TYPE }}-${{ steps.config.outputs.VERSION }}-${{ github.run_number }}"
          bodyFile: "${{ github.workspace }}/SGSI-build-tool/SGSI/build_info.txt"
          token: ${{ secrets.GITHUB_TOKEN }}
